application:
  name: backend
  version: 1

  server:
    host: backend
    port: 8080
    idle-timeout: 5
    shutdown-timeout: 3

  db:
    host: postgres
    port: 5432
    name: appdb
    tls-enabled: false
    auth:
      login: ???
      password: ???

  logger:
    level: info
    development: false
    encoding: json
    outputPaths: [ "stdout", "logs/app.log" ]
    errorOutputPaths: [ "stderr" ]
    encoderConfig:
      timeKey: ts
      levelKey: level
      messageKey: msg
      timeEncoder: iso8601
      levelEncoder: lowercase
      callerEncoder: none