application:
  name: backend
  version: 1

  server:
    host: localhost
    port: 8080
    idle-timeout: 5
    shutdown-timeout: 3
    auth:
      signing-algorithm: HS256
      signing-key: 95EB8AAE6FC49C69A03F0A2C02AF2BA6F9806ADDABE16C6D4AB8A67ED1270612
      exp-sec: 1800

  db:
    host: localhost
    port: 5432
    name: appdb
    tls-enabled: false
    auth:
      login: ???
      password: ???

  logger:
    level: info
    development: false
    encoding: json
    outputPaths: [ "stdout", "logs/app.log" ]
    errorOutputPaths: [ "stderr" ]
    encoderConfig:
      timeKey: ts
      levelKey: level
      messageKey: msg
      timeEncoder: iso8601
      levelEncoder: lowercase
      callerEncoder: none